name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release_extension:
    name: Release Extension
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Make extensions
        run: make all

      - name: Create release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2.4.0
        with:
          draft: false
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            ./JankE-chromium.zip
            ./JankE-firefox.xpi
          name: ${{ github.ref_name }}
